spring:
    application:
        name: logging-logback

    profiles:
        default: local

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
