spring:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                default_batch_fetch_size: 100
        open-in-view: false

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${JDBC_URL}
        username: ${JDBC_USERNAME}
        password: ${JDBC_PASSWORD}

logging:
    #    level.org.springframework.transaction.interceptor: TRACE
    level.org.springframework.orm.jpa: DEBUG

---
spring.config.activate.on-profile: test

spring:
    jpa:
        hibernate:
            ddl-auto: create

---
spring.config.activate.on-profile: local

spring:
    jpa:
        hibernate:
            ddl-auto: create
